package com.oracle.truffle.gradle;

import org.gradle.api.Action;
import org.gradle.api.Plugin;
import org.gradle.api.Project;
import org.gradle.api.artifacts.Configuration;
import org.gradle.api.distribution.DistributionContainer;
import org.gradle.api.tasks.Copy;
import org.gradle.jvm.application.tasks.CreateStartScripts;
import org.gradle.process.JavaForkOptions;

import javax.annotation.Nonnull;
import java.io.IOException;

/**
 * <p>Graal compiler plugin enhances the project so that Graal compiler can be used even on non-Graal JVMs.
 * The version of compiler used can be configured using a {@code graal { graalVersion = "version_string" } }
 * block inside the {@code build.gradle} script.</p>
 *
 * <p>The plugin automatically adds a dependency on the Graal compiler, downloads it to a separate folder,
 * and performs two modifications to ensure the compiler is available in code generated by this project:</p>
 *
 * <p>First, any task that implements {@code JavaForkOptions} (e.g. {@code test}, {@code run}, or any {@code JavaExec}
 * task) has its {@code jvmArgs} extended to enable the Graal compiler (if the running JVM is incompatible with
 * the compiler, a warning is printed).</p>
 *
 * <p>Second, any distribution will also include a separate {@code compiler} directory with the graal compiler
 * and the {@code DEFAULT_JVM_OPTS} in all start scripts are modified to initialize the compiler from this
 * directory.</p>
 */
public class GraalCompilerPlugin implements Plugin<Project> {

    @Override
    public void apply(@Nonnull Project project) {
        // Initialize the Graal config extension.
        GraalExtension config;
        Object extension = project.getExtensions().findByName("graal");
        if (extension != null && !(extension instanceof GraalExtension)) {
            throw new IllegalStateException("Name clash - extension graal already exists.");
        }
        if (extension != null) {
            config = (GraalExtension) extension;
        } else {
            config = project.getExtensions().create("graal", GraalExtension.class);
            config.initDefault(project);
        }

        // Create a graalCompiler configuration which will hold the actual Graal compiler dependencies.
        Configuration graalCompiler = project.getConfigurations().create("graalCompiler")
                .setVisible(false)
                .setDescription("Graal compiler and its dependencies.");
        graalCompiler.setCanBeResolved(true);

        // Lazily add dependency on the graal compiler to the configuration.
        graalCompiler.withDependencies(dependencies ->
            dependencies.add(project.getDependencies().create("org.graalvm.compiler:compiler:"+config.getGraalVersion()))
        );

        // Create the prepareCompiler task which will be used to copy the graal compiler files.
        Copy prepareCompiler = project.getTasks().create("prepareCompiler", Copy.class, task -> task.setGroup("graal"));

        // And configure the task (this has to be done after evaluate because config is not initialized yet).
        project.afterEvaluate(it -> {
            prepareCompiler.from(graalCompiler.getFiles());
            prepareCompiler.into(config.graalCompilerDir);
        });

        // Make all JavaForkOptions tasks use the compiler (and depend on prepareCompiler).
        project.getTasks().all(task -> {
            if (task instanceof JavaForkOptions) {
                task.dependsOn(prepareCompiler);
                task.doFirst(it -> {
                    if (!PluginUtils.isGraalVM()) { // enable compiler only on non-Graal VMs
                        if (!PluginUtils.hasJVMCI()) {  // incompatible JVM - print warning and ignore
                            System.err.println("WARNING: Support for JVM Compiler Interface not detected.");
                            System.err.println("Truffle languages running in interpreter mode only.");
                        } else {
                            JavaForkOptions opts = (JavaForkOptions) it;
                            opts.jvmArgs(
                                    "-XX:+UnlockExperimentalVMOptions", "-XX:+EnableJVMCI",
                                    "--module-path="+config.graalCompilerDir.getAbsolutePath(),
                                    "--upgrade-module-path="+config.graalCompilerDir.getAbsolutePath()
                            );
                        }
                    }
                });
            }
        });

        // Make sure all distributions also include graal compiler in a separate folder.
        // It has to be done after evaluate, because to configure a distribution, we need to resolve graalCompiler.
        project.afterEvaluate(it -> {
            if (project.getExtensions().findByName("distributions") != null) {  // Sometimes there are no distributions...
                project.getExtensions().configure("distributions", (Action<DistributionContainer>) distributions ->
                        distributions.all(distribution ->
                                distribution.getContents().from(graalCompiler.getFiles(), spec -> spec.into("graal-compiler"))
                        )
                );
            }
        });

        // In all CreateStartScripts tasks, replace occurrences of __APP_HOME__ with appropriate environment variable.
        // (This is also used in other plugins that depend on us, but it is defined only once - here)
        project.getTasks().all(task -> {
            if (task instanceof CreateStartScripts) {
                task.doLast(it -> {
                    try {
                        CreateStartScripts scripts = (CreateStartScripts) it;
                        PluginUtils.replaceInFile(scripts.getUnixScript(), "__APP_HOME__", "$APP_HOME");
                        PluginUtils.replaceInFile(scripts.getWindowsScript(), "__APP_HOME__", "%APP_HOME%");
                    } catch (IOException e) {
                        throw new RuntimeException(e);
                    }
                });
            }
        });

        // Add default JVM arguments to the start scripts which will enable the Graal compiler.
        project.getTasks().all(task -> {
            if (task instanceof CreateStartScripts) {
                task.doFirst(it -> {
                    CreateStartScripts scripts = (CreateStartScripts) it;
                    scripts.setDefaultJvmOpts(PluginUtils.appendIterable(scripts.getDefaultJvmOpts(),
                            "-XX:+IgnoreUnrecognizedVMOptions", // A workaround so that we don't have to remove graal compiler on older JVMs.
                            "-XX:+UnlockExperimentalVMOptions",
                            "-XX:+EnableJVMCI",
                            "--module-path=__APP_HOME__/graal-compiler/",
                            "--upgrade-module-path=__APP_HOME__/graal-compiler/"
                    ));
                });
            }
        });
    }

}
